export const documentRels = `<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Target="media/image1.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId8"/>
<Relationship Target="media/image6.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId13"/>
<Relationship Target="media/image11.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId18"/>
<Relationship Target="media/image19.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId26"/>
<Relationship Target="styles.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Id="rId3"/>
<Relationship Target="media/image14.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId21"/>
<Relationship Target="footer1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Id="rId34"/>
<Relationship Target="endnotes.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes" Id="rId7"/>
<Relationship Target="media/image5.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId12"/>
<Relationship Target="media/image10.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId17"/>
<Relationship Target="media/image18.emf" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId25"/>
<Relationship Target="header1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Id="rId33"/>
<Relationship Target="theme/theme1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Id="rId38"/>
<Relationship Target="numbering.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Id="rId2"/>
<Relationship Target="media/image9.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId16"/>
<Relationship Target="media/image13.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId20"/>
<Relationship Target="media/image22.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId29"/>
<Relationship Target="../customXml/item1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" Id="rId1"/>
<Relationship Target="footnotes.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes" Id="rId6"/>
<Relationship Target="media/image4.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId11"/>
<Relationship Target="media/image17.emf" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId24"/>
<Relationship Target="media/image25.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId32"/>
<Relationship Target="fontTable.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Id="rId37"/>
<Relationship Target="webSettings.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Id="rId5"/>
<Relationship Target="media/image8.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId15"/>
<Relationship Target="media/image16.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId23"/>
<Relationship Target="media/image21.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId28"/>
<Relationship Target="footer2.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Id="rId36"/>
<Relationship Target="media/image3.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId10"/>
<Relationship Target="media/image12.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId19"/>
<Relationship Target="media/image24.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId31"/>
<Relationship Target="settings.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Id="rId4"/>
<Relationship Target="media/image2.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId9"/>
<Relationship Target="media/image7.jpeg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId14"/>
<Relationship Target="media/image15.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId22"/>
<Relationship Target="media/image20.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId27"/>
<Relationship Target="media/image23.png" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId30"/>
<Relationship Target="header2.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Id="rId35"/>
</Relationships>`