<template>
	<div id="preloader" class="preloader">
		<div class="preloader__loader">
			<div class="loadingio-spinner-spinner-lubm59c3vdb">
				<div class="ldio-h00fv1la8vf">
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
					<div></div>
				</div>
			</div>
			<span class="preloader__percents"> <span id="percents">0</span>%</span>
		</div>
	</div>
</template>

<script>
export default {}
</script>

<style scoped lang="scss">
.preloader {
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0;
	left: 0;
	&__loader,
	&__percents {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}
	&__percents {
		font-family: 'Montserrat-Medium';
		font-size: large;
		letter-spacing: 2px;
	}
}
// move to global.scss
@keyframes ldio-h00fv1la8vf {
	0% {
		opacity: 1;
	}
	100% {
		opacity: 0;
	}
}
.ldio-h00fv1la8vf div {
	left: 94px;
	top: 48px;
	position: absolute;
	animation: ldio-h00fv1la8vf linear 1s infinite;
	background: #16ffbd;
	width: 12px;
	height: 24px;
	border-radius: 6px / 12px;
	transform-origin: 6px 52px;
}
.ldio-h00fv1la8vf div:nth-child(1) {
	transform: rotate(0deg);
	animation-delay: -0.9166666666666666s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(2) {
	transform: rotate(30deg);
	animation-delay: -0.8333333333333334s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(3) {
	transform: rotate(60deg);
	animation-delay: -0.75s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(4) {
	transform: rotate(90deg);
	animation-delay: -0.6666666666666666s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(5) {
	transform: rotate(120deg);
	animation-delay: -0.5833333333333334s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(6) {
	transform: rotate(150deg);
	animation-delay: -0.5s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(7) {
	transform: rotate(180deg);
	animation-delay: -0.4166666666666667s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(8) {
	transform: rotate(210deg);
	animation-delay: -0.3333333333333333s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(9) {
	transform: rotate(240deg);
	animation-delay: -0.25s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(10) {
	transform: rotate(270deg);
	animation-delay: -0.16666666666666666s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(11) {
	transform: rotate(300deg);
	animation-delay: -0.08333333333333333s;
	background: #16ffbd;
}
.ldio-h00fv1la8vf div:nth-child(12) {
	transform: rotate(330deg);
	animation-delay: 0s;
	background: #16ffbd;
}
.loadingio-spinner-spinner-lubm59c3vdb {
	width: 200px;
	height: 200px;
	display: inline-block;
	overflow: hidden;
	background: none;
}
.ldio-h00fv1la8vf {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-h00fv1la8vf div {
	box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
